### ISSUE TITLE
Not properly working in Nova 10

### ISSUE THREAD

**Issue by pimago** [tpmatthes/Twig.novaextension#11]
Is the twig completion for you also broken in Nova 10? It stops reacting after the the second character I type.

**Comment by tpmatthes** [comment]
Hey, thanks for letting me know! Unfortunately, I can’t reproduce it at the moment as I need to resolve an issue with renewing my license before updating to Nova 10.x.

However, since Nova 10 comes with some big changes to built-in languages and parsing, this may be caused by one of those changes. Can you confirm that it worked fine on Nova 9.x for you?

Also, can you give me a few examples to reproduce it? Does it only happen inside `{% … %}` or for every completion?

**Comment by pimago** [comment]
Yes it worked fine in Nova 9.
Before I could just write dd or for and got suggestions. Now I need to start with the brackets and I get only suggestions when there is just one character. With the second character it stops suggesting.

**Comment by tpmatthes** [comment]
Got it, thanks! I’ll try to solve my license renewal problem with Panic support next week and take a look at this.

**Comment by tpmatthes** [comment]
@pimago I just tried to reproduce this bug with Nova 10.3 and different files/completions. I couldn’t do it, so I downloaded Nova 10.0 from the “Panic File Museum” and was finally able to reproduce it very easily.

With that being said, it seems like it was a bug in Nova and they fixed it with the latest update. Can you confirm this?

**Comment by pimago** [comment]
Ah yes. I just downloaded 10.3 and it looks like they fixed it!

**Comment by tpmatthes** [comment]
Perfect. Thanks for your fast reply! 😄
