### ISSUE TITLE
Highlighting breaks

### ISSUE THREAD

**Issue by pimago** [tpmatthes/Twig.novaextension#7]
Hi, sometimes the highlighting on twig files breaks. Closing and reopening the file fixes it.

Twig 1.6
Nova 6.2

![Screenshot 2021-05-20 at 22 29 14](https://user-images.githubusercontent.com/1803987/119086807-54c99800-ba06-11eb-89b4-5bacfbf81259.png)

**Comment by tpmatthes** [comment]
Hey, thanks for reporting this unwanted behavior! Maybe you can help me solve this by answering some of these questions:

1. Is there any way to reproduce this problem?
2. Does it occur on specific files only?
3. Does it happen with another syntax (html, php etc.) as well?

I’ve noticed this problem 1–2 times in the past, but unfortunately I can’t reproduce it. Since I’m just providing syntax highlighting via regex and it works on the same file after a reload, I think it may be a bug within Nova itself. However, I’m happy to take a closer look, if I can reproduce it. 😊

**Comment by pimago** [comment]
Unfortunately I don't know how to reproduce it. I pay attention when happens the next time. Today it worked fine.
I was only working on craft twig templates a css files so far in Nova.

**Comment by tpmatthes** [comment]
Thank you, I’ll keep an eye on it as well!

**Comment by pimago** [comment]
Hi, I was just able to reproduce it. It happens when adding html around twig.

```
{{ something }}

{% if hello %}Do it!{% endif %}
```

And then I add a html tag around the variable closing it with the </ completion

```
<em>{{ something }}</em>

{% if hello %}Do it!{% endif %}
```

After the </ completion the if statement highlighting breaks. But only if there is an extra line between the variable and the if statement.

**Comment by tpmatthes** [comment]
Hey, it’s great to hear that you’ve found a way to reproduce this bug!

Since it occurs outside of the regular Twig context, I guess it’s a problem with the official HTML syntax definition, which I use, or Nova’s parsing system. I’ll reach out to Panic to discuss this and get back to you when I have more information.

Thanks again! 😊

**Comment by pimago** [comment]
OK, let me know if I can do some testing for you.

**Comment by tpmatthes** [comment]
A quick update from Panic:

```
Thank you for letting us know and the example you've provided! This does look like a bug we have filed for the HTML syntax, as you've mentioned 😅, we'll get this addressed asap! 

I know we're wrapping Nova 7.0, which this may not make it, but I'll make sure this gets on 7.1.
```

I’ll leave this issue open for now and wait for the update to see if I need to do anything afterwards. 🤔

**Comment by pimago** [comment]
Cool. They are fast.

**Comment by tpmatthes** [comment]
Hello again! I’ve just tested Nova 7.1 and it seems like you can’t reproduce this bug anymore. Can you double check this please? 😊

**Comment by pimago** [comment]
Yes I cannot reproduce it anymore. However it super rarely happens with js files. So I guess in the end it was all a Nova problem.

**Comment by tpmatthes** [comment]
Yeah, thank you for reporting anyway! At the end we got it fixed and that’s definitely a good thing. 😄
