### ISSUE TITLE
Comment with HTML and Twig Mix

### ISSUE THREAD

**Issue by pimago** [tpmatthes/Twig.novaextension#9]
Hi, I have similar bug to my previous one. When I comment out a mix of Twig and HTML it breaks after pressing enter.
It's super easy to reproduce. Just comment something out that contains HTML and Twig and then press enter after it.

**Comment by tpmatthes** [comment]
Hey, thanks again for reporting! I couldn’t reproduce this bug in Nova 7.1, but after updating to 7.4, I can successfully reproduce it. Since I’m only providing syntax highlighting via regex and this only occurs after 7.1, this is probably an issue with Nova’s parsing system (like your other issue). Would you be so kind and report this bug to Panic directly? 😊 See: https://nova.app/help/

If I need to do something on my end, be sure to let me know! I’ll leave this open for now.

**Comment by pimago** [comment]
Alright. I will send it to Panic and let you know how the reply.

**Comment by pimago** [comment]
Panic fixed it with the latest update.
